apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.notificationService.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.notificationService.name }}
  ports:
    - port: {{ .Values.notificationService.servicePort }}
      targetPort: {{ .Values.notificationService.serviceTargetPort }}
  type: {{ .Values.notificationService.serviceType }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-preview" .Values.notificationService.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.notificationService.name }}
  ports:
    - port: {{ .Values.notificationService.servicePort }}
      targetPort: {{ .Values.notificationService.serviceTargetPort }}
  type: {{ .Values.notificationService.serviceType }}
{{- end }}
